DECQuando/Synq

synqapp/urls.py
synqapp/views.py

- アクセスしたら文字を表示させるアプリを作成
- Close #3

[add] simple app #3

---

Synq/settings.py

[update] 言語とTimezoneを設定

---

Synq/settings.py

[update] 設定ファイルにアプリを登録

---

Synq/settings.py
requirements.txt

[update] 設定ファイルにbootstrap5を追加
This pq close #7 
実行したコマンド
```
pip install django-bootstrap5
```

[update] django-bootstrap5を導入

---

Dockerfile
README.md
Synq/settings.py

Close #40
Dockerで仮想化できるようにした。
Docker-composeの導入はまだできていない。

Feature/dockerize #40

---

synqapp/admin.py
synqapp/forms.py
synqapp/models.py
synqapp/urls.py
synqapp/views.py
templates/base.html
templates/synqapp/image_detail.html
templates/synqapp/image_form.html
templates/synqapp/image_list.html

This pull request close #44 #2 #10 
- ユーザーの名前を投稿するカンタンなフォーム、一覧、詳細画面を作成
- データベース作成（投稿日とユーザーの名前）
- クラス汎用ビューを導入

Feature/easyform #44

---

templates/base.html

This close #52 
参考記事
- [ヘッダー・フッター （header・footer）の作り方 : Bootstrap の使い方](https://knowledge.cpi.ad.jp/tech/header-footer/)
- [Bootstrap 4で固定ヘッダーと固定フッターを設定する簡単な方法](https://www.marorika.com/entry/bootstrap-sticky)
その他の参考
- [[【Bootstrap】ヘッダー・フッターを固定する](https://bftnagoya.hateblo.jp/entry/2022/06/17/145546)](https://bftnagoya.hateblo.jp/entry/2022/06/17/145546)

[update] headerとfooterを固定

---

synqapp/views.py
templates/synqapp/image_detail.html
templates/synqapp/image_list.html

This closes #48 
- views.pyにtemplate_name, context_object_nameを追加

[update] template_name, context_object_nameを追加

---

templates/base.html
templates/synqapp/image_detail.html

This close #58 
- 詳細画面でも画像を表示するように変更
- 戻るボタンを追加

[update] 詳細画面でも画像を表示

---

synqapp/models.py
synqapp/templatetags/index.py
synqapp/views.py
templates/synqapp/image_list.html

Closes #22 
- models.pyにgroupを追加
- 管理画面から適当にgroup番号を入れる。
- group番号にしたがって、画像をグルーピング表示

Feature/grouping view #22

---

requirements.txt
synqapp/forms.py

Feature/grouping algorithm #63

---

static/css/style.css
templates/base.html
templates/synqapp/includes/img_list_card.html

Closes #66 
- style.cssにobject-fitを追加
- サムネイル画像の表示サイズを揃えた

[update] style.cssにobject-fitを追加

---

synqapp/forms.py

Resolve conflict

---

templates/synqapp/includes/img_list_card.html

[update] loading lazyの導入

---

templates/base.html
templates/synqapp/image_form.html

[update] 投稿フォームの送信ボタンを編集

---

Synq/settings.py
Synq/urls.py
accounts/admin.py
accounts/apps.py
accounts/forms.py
accounts/models.py
accounts/tests.py
accounts/urls.py
accounts/views.py
synqapp/views.py
templates/accounts/login.html
templates/accounts/signup.html
templates/base.html

Feature/add users #11

---

accounts/views.py

[add] 新規登録後の自動ログイン機能を実装

---

synqapp/forms.py
synqapp/models.py
synqapp/views.py

Feature/image with userinfo #90

---

synqapp/views.py

Feature/filter image by user #59

---

.gitignore
Synq/settings.py
requirements.txt
synqapp/models.py
templates/synqapp/includes/img_list_card.html

Feature/generate thumbnail #87

---

synqapp/urls.py

[fix] スラッシュ無しがスラッシュ有りにリダイレクトされるようにした

---

synqapp/forms.py

Feature/grouping each user #96

---

synqapp/forms.py

Feature/image processing in memory #99

---

static/css/style.css
templates/synqapp/image_list.html
templates/synqapp/includes/img_list_card.html

[update] 名前を画像上に表示

---

Synq/settings.py
synqapp/views.py
templates/base.html
templates/synqapp/image_form.html

Close #104 
- プッシュ通知を表示
- [Toasts-Bootstrap](https://getbootstrap.com/docs/5.2/components/toasts/)
- [How to make Bootstrap Toasts not disappear automatically?](https://stackoverflow.com/questions/67033758/how-to-make-bootstrap-toasts-not-disappear-automatically)
- [【BootStrap5】トースト（Toast）の使い方をまとめてみた！動かないときの注意点も紹介！](https://takabus.com/tips/721/)
- [【Bootstrap5】ポップアップの通知メッセージを表示させる：トーストの作成](https://office54.net/iot/bootstrap5/toast-create-message)
- [Djangoで通知メッセージを利用する（メッセージフレームワーク）](https://dot-blog.jp/news/django-messages-frame-work/)

Feature/toast #104

---

static/css/style.css
synqapp/templatetags/index.py
synqapp/views.py
templates/synqapp/image_list.html

Feature/date separate #84

---

synqapp/templatetags/index.py
synqapp/views.py
templates/synqapp/includes/img_list_card.html

Close #108
- グルーピングのボタンを変更
- グルーピングされている枚数を表示

[update] グルーピングのボタンを変更

---

synqapp/forms.py

[fix] RGBAの画像をRGBに処理してからベクトル化を行うようにした。

---

templates/synqapp/image_detail.html

[update] 詳細画面の画像サイズを拡大

---

synqapp/views.py
templates/synqapp/image_form.html

[update] 投稿画面のバナー通知のメッセージを編集

---

synqapp/forms.py
synqapp/views.py

Feature/multiple upload #55
